set_property IOSTANDARD LVCMOS33 [get_ports {control[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {control[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports z]
set_property PACKAGE_PIN M18 [get_ports a]
set_property PACKAGE_PIN P17 [get_ports b]
set_property PACKAGE_PIN P18 [get_ports c]
set_property PACKAGE_PIN M17 [get_ports d]
set_property PACKAGE_PIN H17 [get_ports z]

set_property PACKAGE_PIN L16 [get_ports {control[1]}]
set_property PACKAGE_PIN J15 [get_ports {control[0]}]
